services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=mYAw3s0meB!og
      - POSTGRES_DB=postgres
    volumes:
      - orm-data:/var/lib/postgresql/data

volumes:
  orm-data:
