# Base platform for Postgres.
class Athena::ORM::Platforms::Postgres < Athena::ORM::Platforms::Platform
  # Boolean string literals Postgres accepts in text contexts (e.g. when a
  # value arrives as a string from a hand-rolled query). Anything else falls
  # through to the parent overloads, where `Bool` and `Int` are handled.
  private FALSE_LITERALS = ["f", "false", "n", "no", "off", "0"]

  def convert_from_boolean(value : ::String) : Bool
    !FALSE_LITERALS.includes? value.strip.downcase
  end

  # SQL Declarations

  def boolean_type_declaration_sql(column : Schema::Column) : String
    "BOOLEAN"
  end

  def integer_type_declaration_sql(column : Schema::Column) : String
    "INT #{self.common_integer_type_declaration_sql column}"
  end

  def big_int_type_declaration_sql(column : Schema::Column) : String
    "BIGINT #{self.common_integer_type_declaration_sql column}"
  end

  def guid_type_declaration_sql(column : Schema::Column) : String
    "UUID"
  end

  private def varchar_type_declaration_sql(column : Schema::Column) : String
    sql = "VARCHAR"

    if length = column.length
      sql = "#{sql}(#{length})"
    end

    sql
  end

  private def common_integer_type_declaration_sql(column : Schema::Column) : String
    if column.auto_increment?
      return " GENERATED BY DEFAULT AS IDENTITY"
    end

    ""
  end

  def sequence_next_value_sql(sequence_name : String) : String
    "SELECT NEXTVAL('#{sequence_name}')"
  end

  def empty_identity_insert_sql(quoted_table_name : String, quoted_identifier_column_name) : String
    "INSERT INTO #{quoted_table_name} (#{quoted_identifier_column_name}) VALUES (DEFAULT)"
  end
end
